name: Deploy to shujaurrahman.me

on:
  push:
    branches:
      - master  # Adjust if you want to use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP (optional for linting)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Use PHP version compatible with your server
    
    - name: Validate PHP Syntax (optional)
      run: |
        find . -name "*.php" -print0 | xargs -0 -n1 php -l

    - name: Update "last updated" date in JSON
      run: |
        DATE=$(date +"%d-%m-%Y")
        sed -i "s/last updated on [0-9-]*/last updated on $DATE/" content/colophon.json

    - name: Deploy to InfinityFree via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftpupload.net  # Replace with actual FTP server
        username: if0_36994813  # Your InfinityFree username
        password: ${{ secrets.FTP_PASSWORD }}  # Use a GitHub secret for FTP password
        local-dir: ./  # Assuming your repo's root contains the main domain files
        server-dir: ./htdocs/  # Ensure it ends with a /
        exclude: .git*  # Exclude Git files from deployment 
        
